# Generated by Django 4.0.3 on 2022-06-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True, verbose_name='Номер блока')),
                ('batch_number', models.IntegerField(db_index=True, verbose_name='Номер загрузки')),
            ],
            options={
                'verbose_name': 'Загрузка',
                'verbose_name_plural': 'Загрузки',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_curve', models.JSONField()),
                ('setting_curve', models.JSONField()),
                ('water_exchange_curve', models.JSONField()),
                ('start_time', models.IntegerField()),
                ('stop_time', models.DateTimeField()),
                ('stop_conc', models.FloatField()),
                ('exp_exchange_curve', models.JSONField(null=True)),
                ('block', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Результат расчета',
                'verbose_name_plural': 'Результаты расчетов',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_file', models.FileField(upload_to='', verbose_name='Альбом НФХ')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название таблицы')),
                ('content', models.JSONField(null=True, verbose_name='Значения в таблице')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boric_acid_concentration.block', verbose_name='Блок и загрузка')),
            ],
            options={
                'verbose_name': 'Таблица альбома',
                'verbose_name_plural': 'Таблицы альбома',
            },
        ),
    ]
