# Generated by Django 4.0.3 on 2022-03-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True)),
                ('batch_number', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_before_stop', models.IntegerField(verbose_name='Мощность ЯР до остановки (% от Nном)')),
                ('effective_days_worked', models.IntegerField(verbose_name='Число отработанных эффективных суток')),
                ('rod_height_before_stop', models.IntegerField(verbose_name='Подъем стержней до останова (%)')),
                ('crit_conc_before_stop', models.FloatField(verbose_name='Критическая концентрация БК до останова')),
                ('start_time', models.FloatField(verbose_name='Время, через которое будет осуществляться запуск (часов)')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boric_acid_concentration.block', verbose_name='Блок и загрузка')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_file', models.FileField(upload_to='', verbose_name='Альбом НФХ')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название таблицы')),
                ('content', models.JSONField(null=True, verbose_name='Значения в таблице')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boric_acid_concentration.block', verbose_name='Блок и загрузка')),
            ],
        ),
    ]
