# Generated by Django 4.0.3 on 2022-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='batch_number',
            field=models.IntegerField(db_index=True, verbose_name='Номер загрузки'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(db_index=True, verbose_name='Номер блока'),
        ),
    ]
