# Generated by Django 4.0.3 on 2022-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0002_calculationresult_exp_exchange_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='block',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
