# Generated by Django 4.0.3 on 2022-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_file',
            field=models.ImageField(upload_to='albums/', verbose_name='Альбом'),
        ),
    ]
