# Generated by Django 4.0.3 on 2022-03-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0002_alter_block_batch_number_alter_block_block_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorCalculator',
        ),
    ]
