# Generated by Django 4.0.3 on 2022-06-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0003_calculationresult_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Таблица альбома', 'verbose_name_plural': 'Таблицы альбома'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Загрузка', 'verbose_name_plural': 'Загрузки'},
        ),
        migrations.AlterModelOptions(
            name='calculationresult',
            options={'verbose_name': 'Результат расчета', 'verbose_name_plural': 'Результаты расчетов'},
        ),
    ]
