# Generated by Django 4.0.3 on 2022-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0004_borcalculator_param_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borcalculator',
            name='param_1',
            field=models.FloatField(null=True),
        ),
    ]
