# Generated by Django 4.0.3 on 2022-03-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0005_alter_borcalculator_param_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='borcalculator',
            name='param_2',
            field=models.FloatField(null=True),
        ),
    ]
