# Generated by Django 4.0.3 on 2022-03-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0007_alter_album_album_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borcalculator',
            name='param_1',
        ),
        migrations.RemoveField(
            model_name='borcalculator',
            name='param_2',
        ),
        migrations.AddField(
            model_name='borcalculator',
            name='crit_conc_before_stop',
            field=models.FloatField(null=True, verbose_name='Критическая концентарация БК до останова'),
        ),
        migrations.AddField(
            model_name='borcalculator',
            name='effective_days_worked',
            field=models.IntegerField(null=True, verbose_name='Число отработанных эффективных суток'),
        ),
        migrations.AddField(
            model_name='borcalculator',
            name='power_before_stop',
            field=models.IntegerField(null=True, verbose_name='Мощность ЯР до остановки (% от Nном)'),
        ),
        migrations.AddField(
            model_name='borcalculator',
            name='rod_height_before_stop',
            field=models.IntegerField(null=True, verbose_name='Подъем стержней до останова (%)'),
        ),
        migrations.AddField(
            model_name='borcalculator',
            name='start_time',
            field=models.FloatField(null=True, verbose_name='Время, через которое будет осуществляться запуск (часов)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_file',
            field=models.FileField(upload_to='', verbose_name='Альбом НФХ'),
        ),
    ]
