# Generated by Django 4.0.3 on 2022-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0008_remove_borcalculator_param_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='table1',
            field=models.JSONField(null=True, verbose_name='Таблица 1'),
        ),
    ]
