# Generated by Django 4.0.3 on 2022-03-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0009_album_table1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='table1',
        ),
    ]
