# Generated by Django 4.0.3 on 2022-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boric_acid_concentration', '0010_remove_album_table1'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='content',
            field=models.JSONField(null=True, verbose_name='Значения в таблице'),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название таблицы'),
        ),
    ]
